name: Lint Code Base

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_POWERSHELL: true
          DISABLE_ERRORS: false
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: tap
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Report as an artifact
        uses: actions/upload-artifact@master
        with:
          name: linter-report
          path: "${{ github.workspace }}/super-linter.report/"
