name: Lint Code Base

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_POWERSHELL: true
          OUTPUT_DETAILS: simpler 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
